force-app/main/default/objects/ATMFee__mdt/ATMFee__mdt.object-meta.xml
<CustomObject>
    <label>ATM Fee</label>
    <pluralLabel>ATM Fees</pluralLabel>
</CustomObject>

force-app/main/default/objects/ATMFee__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <default>true</default>
                <label>DE</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ATMFee__mdt/fields/Fee__c.field-meta.xml
<CustomField>
    <fullName>Fee__c</fullName>
    <label>Fee</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/ATMFee__mdt/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CardReplacementCost__mdt/CardReplacementCost__mdt.object-meta.xml
<CustomObject>
    <label>Card Replacement Cost</label>
    <pluralLabel>Card Replacement Costs</pluralLabel>
</CustomObject>

force-app/main/default/objects/CardReplacementCost__mdt/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <label>Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/CardReplacementCost__mdt/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
                <default>true</default>
                <label>Standard</label>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>External System UUID</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>36</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Home_Country__c.field-meta.xml
<CustomField>
    <fullName>Home_Country__c</fullName>
    <label>Home Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Standard</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Metal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductCost__mdt/ProductCost__mdt.object-meta.xml
<CustomObject>
    <label>Product Cost</label>
    <pluralLabel>Product Costs</pluralLabel>
</CustomObject>

force-app/main/default/objects/ProductCost__mdt/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DE</fullName>
                <default>true</default>
                <label>DE</label>
            </value>
            <value>
                <fullName>FR</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductCost__mdt/fields/Currency__c.field-meta.xml
<CustomField>
    <fullName>Currency__c</fullName>
    <label>Currency</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EUR</fullName>
                <default>true</default>
                <label>EUR</label>
            </value>
            <value>
                <fullName>GBP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactProductInfoService.cls
@RestResource(urlMapping='/v1/ContactProductInfo/*')
global with sharing class ContactProductInfoService {

    @HttpGet
    global static void getProductInfo() {
        RestRequest request = RestContext.request;
        String contactExternalId = request.requestURI.substring(request.requestURI.lastIndexOf('/')+1);
        
        Contact contact = [
            SELECT Id, Product__c, Home_Country__c 
            FROM Contact 
            WHERE ExternalId__c = :contactExternalId
            LIMIT 1
        ];
        
        if (contact != null) {
            Map<String, Object> result = new Map<String, Object> {
                'Product' => contact.Product__c,
                'Home Country' => contact.Home_Country__c
            };

            // Retrieve ATM Fees
            ATMFee__mdt atmFee = [
                SELECT Fee__c 
                FROM ATMFee__mdt 
                WHERE Product__c = :contact.Product__c AND Country__c = :contact.Home_Country__c
                LIMIT 1
            ];
            if (atmFee != null) {
               result.put('ATM Fee', atmFee.Fee__c);
            }
            // Retrieve Card Replacement Costs
            CardReplacementCost__mdt cardReplacementCost = [
                SELECT Cost__c, Currency__c 
                FROM CardReplacementCost__mdt 
                WHERE Product__c = :contact.Product__c AND Country__c = :contact.Home_Country__c
                LIMIT 1
            ];
            if (cardReplacementCost != null) {
                result.put('Card Replacement Cost', cardReplacementCost.Cost__c);
                result.put('Card Replacement Currency', cardReplacementCost.Currency__c);
            }

            // Retrieve Product Costs
            ProductCost__mdt productCost = [
                SELECT Cost__c, Currency__c 
                FROM ProductCost__mdt 
                WHERE Product__c = :contact.Product__c AND Country__c = :contact.Home_Country__c
                LIMIT 1
            ];
            if (productCost != null) {
                result.put('Product Cost', productCost.Cost__c);
                result.put('Product Currency', productCost.Currency__c);
            }

            RestContext.response.responseBody = Blob.valueOf(JSON.serialize(result));
            RestContext.response.statusCode = 200;
        } else {
            RestContext.response.responseBody = Blob.valueOf('Contact not found');
            RestContext.response.statusCode = 404;
        }
    }
}